export enum Tag {
  // Some system tags
  Health = 'Health',
  Mana = 'Mana',
  Resistance = 'Resistance',
  Damage = 'Damage',
  Multiplier = 'Multiplier',
  SkillMultiplier = 'Skill Damage Multiplier',
  HitRate = 'Hit Rate',
  Penetration = 'Penetration',
  Speed = 'Speed',
  Stats = 'Stats',
  Special = 'Special',

  // Rune tags
  Attack = 'Attack',
  Spell = 'Spell',
  DamageOverTime = 'DoT',
  Minion = 'Minion',
  DefenceEnhance = 'Defence Enhance',
  AttackEnhance = 'Attack Enhance',
  Duration = 'Duration',
  Shout = 'Shout',
  AreaOfEffect = 'Area of Effect',
  Strike = 'Strike',
  Projectile = 'Projectile',
  Fire = 'Fire',
  Cold = 'Cold',
  Lightning = 'Lightning',
  Poison = 'Poison',
  Elemental = 'Elemental',
  Physical = 'Physical',
  Totem = 'Totem',
  Movement = 'Movement',
  Toggle = 'Toggle',
  DefenceSeal = 'Defence Seal',
}
